baseURL = "/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "data-science"
disqusShortname = "yourdiscussshortname"

preserveTaxonomyNames = true

# sectionPagesMenu = "main"

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

[params]
  author = "Amber Thomas"




[params.social]
  email = "AmberThomasMSc@gmail.com"
  twitter = "https://twitter.com/ProQuesAsker"
  github = "https://www.github.com/ProQuestionAsker"
  linkedin = "https://www.linkedin.com/in/amberrthomas/"
  stackoverflow = ""
  facebook = ""
  instagram = ""
  googleplus = ""
