baseURL = "/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "data-science"
disqusShortname = "yourdiscussshortname"

preserveTaxonomyNames = true

# sectionPagesMenu = "main"

[params]
  author = "Amber Thomas"


[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"
