# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Blogfolio Bricks"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = ""
homepage = "http://example.com/"
tags = ["blog", "responsive", "portfolio", "dark", "light", "contact form", "Highlight.js"]
features = []
min_version = "0.38"

[author]
  name = "Amber Thomas"
  homepage = "amber.rbind.io"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
